-- 코드를 입력하세요
SELECT B.AUTHOR_ID, 
    B.AUTHOR_NAME,
    A.CATEGORY,
    SUM(C.SALES * A.PRICE)  AS TOTAL_PRICE
FROM BOOK A, AUTHOR B, BOOK_SALES C
WHERE A.BOOK_ID=C.BOOK_ID 
    AND A.AUTHOR_ID=B.AUTHOR_ID
    AND TO_CHAR(C.SALES_DATE, 'YYYY-MM')='2022-01'
GROUP BY B.AUTHOR_ID, 
    A.CATEGORY, 
    B.AUTHOR_NAME
ORDER BY B.AUTHOR_ID ASC, A.CATEGORY DESC
;