-- 코드를 작성해주세요

SELECT A.ID, 
    CASE
        WHEN B.CHILD_COUNT IS NULL THEN 0
        ELSE B.CHILD_COUNT
    END AS CHILD_COUNT
FROM ECOLI_DATA A LEFT OUTER JOIN (
    SELECT A.ID, COUNT(*) AS CHILD_COUNT
    FROM ECOLI_DATA A, ECOLI_DATA B
    WHERE B.PARENT_ID=A.ID
    GROUP BY A.ID
    ) B
ON A.ID=B.ID
ORDER BY A.ID
;