-- 코드를 입력하세요

-- 빌릴 수 없는 차 쿼리


-- 종류와 대여 금액이 맞는 자동차 쿼리
SELECT A.CAR_ID, 
    A.CAR_TYPE, 
    MIN((A.DAILY_FEE * (100-B.DISCOUNT_RATE) / 100) * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR A, CAR_RENTAL_COMPANY_DISCOUNT_PLAN B
WHERE A.CAR_TYPE=B.CAR_TYPE(+)
    AND B.DURATION_TYPE NOT LIKE '%90%'
    AND (A.CAR_TYPE='SUV' OR A.CAR_TYPE='세단')
    AND (A.DAILY_FEE * (100-B.DISCOUNT_RATE) / 100) * 30 >= 500000
    AND (A.DAILY_FEE * (100-B.DISCOUNT_RATE) / 100) * 30 < 2000000
    AND CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE TO_CHAR(START_DATE, 'YYYY-MM-DD') <= '2022-11-30'
            AND TO_CHAR(END_dATE, 'YYYY-MM-DD') >= '2022-11-01'
        GROUP BY CAR_ID    
    )
GROUP BY A.CAR_ID, A.CAR_TYPE
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC
;