-- 코드를 입력하세요
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO
WHERE REST_ID IN (
    SELECT A.REST_ID
    FROM REST_INFO A
    WHERE A.FAVORITES IN (
        SELECT MAX(FAVORITES)
        FROM REST_INFO
        WHERE FOOD_TYPE=A.FOOD_TYPE
    )
)
ORDER BY FOOD_TYPE DESC;
