-- 코드를 작성해주세요

SELECT ID,
    CASE
        WHEN ROWNUM / (SELECT COUNT(*) FROM ECOLI_DATA) * 100 <= 25 THEN 'LOW'
        WHEN ROWNUM / (SELECT COUNT(*) FROM ECOLI_DATA) * 100 <= 50 THEN 'MEDIUM'
        WHEN ROWNUM / (SELECT COUNT(*) FROM ECOLI_DATA) * 100 <= 75 THEN 'HIGH'
        ELSE 'CRITICAL'
    END AS COLONY_NAME
FROM (
    SELECT ID, ROW_NUMBER() OVER ( ORDER BY SIZE_OF_COLONY ) AS ROWNUM
    FROM ECOLI_DATA
    )A
ORDER BY ID
;
