-- 코드를 입력하세요
SELECT A.ANIMAL_ID, A.ANIMAL_TYPE, A.NAME
FROM ANIMAL_INS A, ANIMAL_OUTS B
WHERE A.ANIMAL_ID=B.ANIMAL_ID
    AND UPPER(A.SEX_UPON_INTAKE) LIKE '%INTACT%'
    AND (UPPER(B.SEX_UPON_OUTCOME) LIKE '%SPAYED%'
        OR UPPER(B.SEX_UPON_OUTCOME) LIKE '%NEUTERED%'
        )
ORDER BY ANIMAL_ID;