-- 코드를 입력하세요
SELECT 
    A.CAR_ID, 
    ROUND(AVG(A.END_DATE-A.START_DATE+1), 1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
WHERE 
    (
    SELECT ROUND(AVG(END_DATE-START_DATE+1),1)
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE CAR_ID = A.CAR_ID
    GROUP BY CAR_ID
    ) >= 7
GROUP BY A.CAR_ID
ORDER BY AVERAGE_DURATION DESC, A.CAR_ID DESC;