-- -- 코드를 입력하세요

SELECT YEAR, MONTH, 
    COUNT(*) AS PUCHASED_USERS, 
    ROUND(COUNT(*) / (SELECT COUNT(*) FROM USER_INFO 
             WHERE TO_CHAR(JOINED,'YYYY')='2021'), 1) AS PUCHASED_RATIO
FROM
    (
    SELECT TO_CHAR(SALES_DATE, 'YYYY') AS YEAR, 
        TO_NUMBER(TO_CHAR(SALES_DATE, 'MM')) AS MONTH,
        A.USER_ID,
        SUM(A.SALES_AMOUNT) AS AMOUNT
    FROM ONLINE_SALE A,
        USER_INFO B
    WHERE A.USER_ID=B.USER_ID
        AND TO_CHAR(B.JOINED, 'YYYY')='2021'
    GROUP BY TO_CHAR(A.SALES_DATE, 'YYYY'),
        TO_NUMBER(TO_CHAR(A.SALES_DATE, 'MM')),
        A.USER_ID
    )
GROUP BY YEAR, MONTH
ORDER BY YEAR ASC, MONTH ASC
;