SELECT A.CAR_ID, 
    CASE
        WHEN B.CAR_ID IS NULL THEN '대여 가능'
        ELSE '대여중'
    END AS AVAILABILITY
FROM (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        GROUP BY CAR_ID
        ORDER BY CAR_ID
    ) A,
    (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE TO_CHAR(START_DATE, 'YYYY-MM-DD') <= '2022-10-16'
            AND TO_CHAR(END_DATE, 'YYYY-MM-DD') >= '2022-10-16'
        ORDER BY CAR_ID, START_DATE, END_DATE
    ) B
WHERE a.car_id = b.car_id(+)
ORDER BY A.CAR_ID DESC;