-- -- 코드를 입력하세요

-- -- 가격 할인 정책이 없을 때도 생각하여서 적용해야해.

SELECT C.HISTORY_ID, MIN(D.DAILY_FEE*(C.END_DATE-C.START_DATE+1)) AS FEE
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY C, 
    (SELECT A.CAR_ID, 
        SUBSTR(B.DURATION_TYPE, 0, 1) AS DURATION_TYPE,
        A.DAILY_FEE * (100-DISCOUNT_RATE) / 100 AS DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR A, CAR_RENTAL_COMPANY_DISCOUNT_PLAN B
    WHERE A.CAR_TYPE = B.CAR_TYPE
        AND A.CAR_TYPE='트럭'

    UNION ALL

    SELECT CAR_ID, 
        '0' AS DURATION_TYPE,
        DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE='트럭') D
WHERE C.CAR_ID=D.CAR_ID
    AND(
        ((D.DURATION_TYPE=3
             OR D.DURATION_TYPE=9)
            AND D.DURATION_TYPE*10 <= C.END_DATE-C.START_DATE+1)
        OR (D.DURATION_TYPE=7 AND D.DURATION_TYPE <= C.END_DATE-C.START_DATE+1)
        OR (D.DURATION_TYPE=0)
    )
GROUP BY C.HISTORY_ID
ORDER BY FEE DESC, C.HISTORY_ID DESC
;

    