-- 코드를 입력하세요
SELECT FLAVOR
FROM(
    SELECT A.TOTAL_ORDER + B.TOTAL_ORDER AS TOTAL_ORDER, A.FLAVOR
    FROM (
            SELECT SUM(TOTAL_ORDER) AS TOTAL_ORDER, FLAVOR
            FROM JULY
            GROUP BY FLAVOR
        ) A,
        FIRST_HALF B
    WHERE A.FLAVOR=B.FLAVOR
    ORDER BY TOTAL_ORDER DESC
    )
WHERE ROWNUM <= 3
;