-- 코드를 입력하세요
SELECT B.HOUR, COUNT(A.DATETIME) AS COUNT
FROM 
    ANIMAL_OUTS A
RIGHT OUTER JOIN
    (SELECT LEVEL-1 AS HOUR 
     FROM DUAL 
     CONNECT BY LEVEL<=24) B
ON TO_NUMBER(TO_CHAR(A.DATETIME, 'HH24')) = B.HOUR
GROUP BY B.HOUR
ORDER BY B.HOUR
;

