-- 코드를 작성해주세요
SELECT A.ID, A.EMAIL, A.FIRST_NAME, A.LAST_NAME
FROM DEVELOPERS A, SKILLCODES B
WHERE UPPER(B.CATEGORY)='FRONT END'
    AND A.SKILL_CODE & B.CODE = B.CODE
GROUP BY A.ID, A.EMAIL, A.FIRST_NAME, A.LAST_NAME
ORDER BY A.ID
;