-- 코드를 작성해주세요
SELECT TEMP.ITEM_ID, TEMP.ITEM_NAME, TEMP.RARITY
FROM ITEM_INFO INFO, ITEM_TREE TREE, ITEM_INFO TEMP
WHERE INFO.ITEM_ID = TREE.PARENT_ITEM_ID
AND TREE.ITEM_ID = TEMP.ITEM_ID
AND INFO.RARITY="RARE"
ORDER BY ITEM_ID DESC;